# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 352)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButtonSource = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.pushButtonSource.sizePolicy().hasHeightForWidth())
        self.pushButtonSource.setSizePolicy(sizePolicy)
        self.pushButtonSource.setObjectName("pushButtonSource")
        self.verticalLayout_3.addWidget(self.pushButtonSource)
        self.pushButtonDestination = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDestination.sizePolicy().hasHeightForWidth())
        self.pushButtonDestination.setSizePolicy(sizePolicy)
        self.pushButtonDestination.setObjectName("pushButtonDestination")
        self.verticalLayout_3.addWidget(self.pushButtonDestination)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.spinBoxThreads = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxThreads.setMinimum(1)
        self.spinBoxThreads.setObjectName("spinBoxThreads")
        self.gridLayout.addWidget(self.spinBoxThreads, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.spinBoxQuality = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxQuality.setMaximum(100)
        self.spinBoxQuality.setObjectName("spinBoxQuality")
        self.gridLayout.addWidget(self.spinBoxQuality, 0, 2, 1, 1)
        self.pushButtonCompress = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCompress.setObjectName("pushButtonCompress")
        self.gridLayout.addWidget(self.pushButtonCompress, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidgetFiles = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetFiles.sizePolicy().hasHeightForWidth())
        self.listWidgetFiles.setSizePolicy(sizePolicy)
        self.listWidgetFiles.setMinimumSize(QtCore.QSize(0, 74))
        self.listWidgetFiles.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidgetFiles.setObjectName("listWidgetFiles")
        self.verticalLayout_4.addWidget(self.listWidgetFiles)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 2, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditSource = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSource.setObjectName("lineEditSource")
        self.verticalLayout.addWidget(self.lineEditSource)
        self.lineEditDestination = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDestination.setObjectName("lineEditDestination")
        self.verticalLayout.addWidget(self.lineEditDestination)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ImageCompressor"))
        self.pushButtonSource.setText(_translate("MainWindow", "Source..."))
        self.pushButtonDestination.setText(_translate("MainWindow", "Destination..."))
        self.label.setText(_translate("MainWindow", "Number of threads:"))
        self.label_2.setText(_translate("MainWindow", "Quality: (0 - 100)"))
        self.pushButtonCompress.setText(_translate("MainWindow", "Compress"))

